title:  Ame's Thoughts on the world
author: WonderfulAme
theme: minima

description: "Planet Earth"

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true


url: https://WonderfulAme.github.io/


