title:  Ame's Thoughts on the world
author: WonderfulAme
theme: minima

description: "Planet Earth"

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Add a search button to the navbar
post_search: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true


